name: Actions Runner Controller Demo
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: test-runner-scale-set-1
    container:
      image: node:18-slim
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"